#! /bin/bash
### BEGIN INIT INFO
# Provides:          	controld
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description: Control daemon
### END INIT INFO

# load configuration parameters
. /tmp/geofox.conf

NAME=controld
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DAEMON=/usr/local/bin/$NAME
PIDFILE=/var/run/$NAME.pid
DESC="Control daemon"
OPTS="$OUTPUT1_ID $CONTROL1_FILE $OUTPUT2_ID $CONTROL2_FILE $OUTPUT3_ID $CONTROL3_FILE $OUTPUT4_ID $CONTROL4_FILE $OUTPUT5_ID $CONTROL5_FILE $OUTPUT6_ID $CONTROL6_FILE $OUTPUT7_ID $CONTROL7_FILE $OUTPUT8_ID $CONTROL8_FILE"

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
    start)
	echo "Start $DESC"
	start-stop-daemon --start --quiet --background --oknodo --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $OPTS
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
	echo "Stop $DESC"
	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
	;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
