#! /bin/bash
### BEGIN INIT INFO
# Provides:          	mqttc
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description: MQTT client daemon
### END INIT INFO

# load configuration parameters
. /tmp/geofox.conf

NAME=mqttc
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DAEMON=/usr/local/bin/$NAME-device.py
PIDFILE=/var/run/$NAME.pid
DESC="MQTT client daemon"
OPTS="--brokerAddr $BROKER_ADDR --plantId $PLANTID --extCmd $MODBUS_CLIENT --ipAddr $MODBUS_DEVICE_IP"

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
    start)
	echo "Start $DESC"
	start-stop-daemon --start --quiet --background --oknodo --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $OPTS
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
	echo "Stop $DESC"
	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
	;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
