#! /bin/bash
### BEGIN INIT INFO
# Provides:          	modbus_reg_scanner
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description: Modbus register scanner
### END INIT INFO

NAME=modbus_register_scanner
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DAEMON=/usr/local/bin/$NAME.sh
PIDFILE=/var/run/$NAME.pid
DESC="Modbus register scanner"
#OPTS="$INFRAREAD_DELAY $INFRALOOP_DELAY $GEOFOX_LOG_FORMAT" #delays in seconds between successive reads or read cycles
OPTS=""

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
    start)
	echo "Start $DESC"
	start-stop-daemon --start --quiet --background --oknodo --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $OPTS
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
	echo "Stop $DESC"
	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
	;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
